services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: mathtutor-postgres
    environment:
      - POSTGRES_DB=MathTutorDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-YourStrong@Passw0rd}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mathtutor-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend API with PostgreSQL
  backend:
    build:
      context: ./MathBackend
      dockerfile: Dockerfile
    container_name: mathtutor-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
      - DatabaseProvider=PostgreSQL
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=MathTutorDb;Username=postgres;Password=${POSTGRES_PASSWORD:-YourStrong@Passw0rd}
      - JwtSettings__Secret=${JWT_SECRET:-YourSuperSecretKeyThatShouldBeAtLeast32CharactersLongForProduction}
      - AI__Gemini__ApiKey=${GEMINI_API_KEY}
    ports:
      - "5000:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mathtutor-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend
  frontend:
    build:
      context: ./MathFrontend/VueJS-User-Management
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:5000/api
    container_name: mathtutor-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - mathtutor-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  postgres_data:
    driver: local

networks:
  mathtutor-network:
    driver: bridge
